// <auto-generated />
namespace YousafGill.Tutorials.IdentityUserCustomFields.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedfirstandlastname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfirstandlastname));
        
        string IMigrationMetadata.Id
        {
            get { return "202002292216576_'addedfirstandlastname'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
